id = "golden-wasp"
name = "Golden Wasp Theme"
version = "0.1.0"
schema_version = 1
authors = ["Mohamed Ahmed"]
description = "My custom dark charcoal + gold theme for Zed"
repository = "https://github.com/mohamedxyz/golden-wasp-theme-for-zed"
